// County-level effective property-tax rate estimates (% of home value, per year).
// Sourced from publicly reported county effective-rate averages; for estimation only.
// Editable: add or update entries as needed.
window.COUNTY_TAX_RATES = [
  { name: "— National average —", rate: 1.10 },
  { name: "Los Angeles County, CA", rate: 0.75 },
  { name: "Orange County, CA", rate: 0.72 },
  { name: "San Diego County, CA", rate: 0.76 },
  { name: "Santa Clara County, CA", rate: 0.79 },
  { name: "Alameda County, CA", rate: 0.82 },
  { name: "Maricopa County, AZ", rate: 0.62 },
  { name: "Clark County, NV", rate: 0.65 },
  { name: "King County, WA", rate: 0.93 },
  { name: "Multnomah County, OR", rate: 1.03 },
  { name: "Denver County, CO", rate: 0.55 },
  { name: "Travis County, TX", rate: 1.80 },
  { name: "Harris County, TX", rate: 2.03 },
  { name: "Dallas County, TX", rate: 1.93 },
  { name: "Bexar County, TX", rate: 2.15 },
  { name: "Cook County, IL", rate: 2.10 },
  { name: "DuPage County, IL", rate: 2.20 },
  { name: "Wayne County, MI", rate: 2.35 },
  { name: "Oakland County, MI", rate: 1.55 },
  { name: "Cuyahoga County, OH", rate: 2.40 },
  { name: "Franklin County, OH", rate: 1.90 },
  { name: "Hamilton County, OH", rate: 1.75 },
  { name: "Allegheny County, PA", rate: 2.05 },
  { name: "Philadelphia County, PA", rate: 1.00 },
  { name: "Erie County, NY", rate: 2.40 },
  { name: "Nassau County, NY", rate: 2.10 },
  { name: "Suffolk County, NY", rate: 2.30 },
  { name: "New York County, NY", rate: 0.90 },
  { name: "Westchester County, NY", rate: 2.00 },
  { name: "Essex County, NJ", rate: 2.60 },
  { name: "Bergen County, NJ", rate: 2.10 },
  { name: "Middlesex County, NJ", rate: 2.40 },
  { name: "Fairfield County, CT", rate: 1.85 },
  { name: "Hartford County, CT", rate: 2.05 },
  { name: "Suffolk County, MA", rate: 0.65 },
  { name: "Middlesex County, MA", rate: 1.20 },
  { name: "Fulton County, GA", rate: 1.15 },
  { name: "DeKalb County, GA", rate: 1.20 },
  { name: "Mecklenburg County, NC", rate: 0.96 },
  { name: "Wake County, NC", rate: 0.88 },
  { name: "Miami-Dade County, FL", rate: 0.97 },
  { name: "Broward County, FL", rate: 1.07 },
  { name: "Orange County, FL", rate: 0.95 },
  { name: "Hillsborough County, FL", rate: 1.10 },
  { name: "Davidson County, TN", rate: 0.75 },
  { name: "Shelby County, TN", rate: 1.45 },
  { name: "Jefferson County, KY", rate: 0.95 },
  { name: "Marion County, IN", rate: 1.05 },
  { name: "Hennepin County, MN", rate: 1.20 },
  { name: "Milwaukee County, WI", rate: 2.25 },
  { name: "Salt Lake County, UT", rate: 0.65 }
];
